import { useState } from "react";
import "./Schedule.css";

function Schedule() {
  // Mock subjects (should come from planner context/state in real app)
  const [subjects] = useState([
    { id: 1, name: "Mathematics", examDate: "2025-05-15", priority: "High", hoursPerDay: 2, color: "#1e3a8a" },
    { id: 2, name: "Physics", examDate: "2025-05-20", priority: "Medium", hoursPerDay: 1.5, color: "#dc2626" },
    { id: 3, name: "Computer Science", examDate: "2025-05-10", priority: "High", hoursPerDay: 2.5, color: "#facc15" },
    { id: 4, name: "English", examDate: "2025-05-25", priority: "Low", hoursPerDay: 1, color: "#10b981" },
  ]);

  // Generate schedule for each day of the week (simplified – assign subjects to fixed times)
  // In a real app, this would be generated by an algorithm based on priorities and deadlines.
  const weekDays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  
  // Mock schedule data: each day has a list of sessions
  const scheduleData = {
    Monday: [
      { time: "09:00 - 10:30", subject: "Mathematics", duration: "1.5h", color: "#1e3a8a" },
      { time: "11:00 - 12:30", subject: "Physics", duration: "1.5h", color: "#dc2626" },
      { time: "14:00 - 15:30", subject: "Computer Science", duration: "1.5h", color: "#facc15" },
    ],
    Tuesday: [
      { time: "09:00 - 10:30", subject: "Computer Science", duration: "1.5h", color: "#facc15" },
      { time: "11:00 - 12:00", subject: "English", duration: "1h", color: "#10b981" },
      { time: "15:00 - 17:00", subject: "Mathematics", duration: "2h", color: "#1e3a8a" },
    ],
    Wednesday: [
      { time: "09:00 - 11:00", subject: "Mathematics", duration: "2h", color: "#1e3a8a" },
      { time: "13:00 - 14:30", subject: "Physics", duration: "1.5h", color: "#dc2626" },
      { time: "15:00 - 16:30", subject: "Computer Science", duration: "1.5h", color: "#facc15" },
    ],
    Thursday: [
      { time: "10:00 - 11:30", subject: "English", duration: "1.5h", color: "#10b981" },
      { time: "13:00 - 14:30", subject: "Mathematics", duration: "1.5h", color: "#1e3a8a" },
      { time: "15:00 - 16:30", subject: "Physics", duration: "1.5h", color: "#dc2626" },
    ],
    Friday: [
      { time: "09:00 - 10:30", subject: "Computer Science", duration: "1.5h", color: "#facc15" },
      { time: "11:00 - 12:30", subject: "Mathematics", duration: "1.5h", color: "#1e3a8a" },
      { time: "14:00 - 15:00", subject: "English", duration: "1h", color: "#10b981" },
    ],
    Saturday: [
      { time: "10:00 - 12:00", subject: "Physics", duration: "2h", color: "#dc2626" },
      { time: "13:00 - 15:00", subject: "Computer Science", duration: "2h", color: "#facc15" },
    ],
    Sunday: [
      { time: "Rest Day", subject: "No study scheduled", duration: "", color: "#9ca3af" },
    ],
  };

  // Current date to highlight today
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long' });

  return (
    <div className="schedule-page">
      <h1>Weekly Study Schedule</h1>
      <p className="schedule-intro">Plan your week effectively. Sessions are color-coded by subject.</p>

      <div className="week-schedule">
        {weekDays.map(day => (
          <div key={day} className={`day-card ${day === today ? 'today' : ''}`}>
            <h3 className="day-header">{day}</h3>
            <div className="sessions">
              {scheduleData[day]?.map((session, idx) => (
                <div key={idx} className="session-item" style={{ borderLeftColor: session.color }}>
                  <span className="session-time">{session.time}</span>
                  <span className="session-subject" style={{ color: session.color }}>{session.subject}</span>
                  {session.duration && <span className="session-duration">{session.duration}</span>}
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Legend */}
      <div className="schedule-legend">
        <h4>Subjects</h4>
        <div className="legend-items">
          {subjects.map(sub => (
            <div key={sub.id} className="legend-item">
              <span className="legend-color" style={{ backgroundColor: sub.color }}></span>
              <span>{sub.name}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Schedule;